### ISSUE TITLE
Yandex inflect is no more accessable

### ISSUE THREAD

**Issue by bubnovKelnik** [mmjurov/yandex-inflector#2]
http://export.yandex.ru/inflect.xml return 403
http://export.yandex.ru/inflect.xml?name=Новость return 404

**Comment by mmjurov** [comment]
Черт ... 
значит будем искать альтернативы ...

**Comment by mmjurov** [comment]
@bubnovKelnik Спасибо за инфо!

**Comment by mmjurov** [comment]
Добавил https://github.com/mmjurov/inflector
