### ISSUE TITLE
Сделать библиотеку провайдером над разными сервисами

### ISSUE THREAD

**Issue by mmjurov** [mmjurov/yandex-inflector#3]
В качестве альтернатив нашел пару других сервисов:
https://htmlweb.ru/service/sklonjator.php
http://morpher.ru/

В будущем может еще что-то найду, или может заработает снова сервис от яндекса. 

Нужно сделать какой-то провайдер, который сможет выбирать данные из разных сервисов и выдавать их в едином стиле

**Comment by bubnovKelnik** [comment]
Не получится мегамонстр?

**Comment by mmjurov** [comment]
Да ну, вряд ли. По одному классу на каждый обработчик стороннего склонятора. Общий интерфейс для всех склоняторов. 
Не думаю, что это будет большой проблемой. На скорость работы точно сильного влияния не окажет. Зато можно будет использовать несколько сервисов, если один из них отвалится, или у него кончится лимит

**Comment by bubnovKelnik** [comment]
Для своих целей перешел на standalone cijic/phpmorphy
Ни от кого теперь не завишу.

Как собираю падежи - можно посмотреть в 
https://github.com/bubnovKelnik/twig-declension/blob/master/src/BubnovKelnik/TwigDeclensionBundle/Twig/Extension/TwigDeclensionExtension.php

Метод getDeclensions

**Comment by bubnovKelnik** [comment]
Библиотека позволяет получить все формы слова во всех падежах, в том числе во множественном числе.

**Comment by mmjurov** [comment]
круто! будет как один из адаптеров:) Спасибо, сам тоже попробую эту библиотечку (появилась острая нужда). Не знал о ее существовании.
